### ISSUE TITLE
Issue running the container!

### ISSUE THREAD

**Issue by periatrubikx** [elamperti/docker-mkdocs#1]
I get the following error when i execute the following:
docker run -it -v /${PWD}:/doc -p 8000:8000 elamperti/docker-mkdocs serve -a 0.0.0.0:8000

INFO    -  Building documentation... 
ERROR   -  Config value: 'docs_dir'. Error: The path /doc/docs isn't an existing directory.

**Comment by periatrubikx** [comment]
Never mind; i had to have /docs and /site directories created in my local mkdocs folder.

**Comment by elamperti** [comment]
Glad you were able to solve it! :slightly_smiling_face:
